<?php

namespace Innobrain\SoakTime;

final class IntegrityLockFile
{
    private const SCHEMA_VERSION = 2;

    private const README = [
        'Generated by innobrain/soak-time. Records package integrity evidence',
        'for every version installed into this project. Commit alongside composer.lock.',
        'A mismatch against recorded hashes, source references, or canonical URLs',
        'hard-fails the run — the signal of an altered historical release.',
    ];

    /** @var array<string, array<string, IntegrityEntry>> */
    private array $entries = [];

    public function __construct(public readonly string $path) {}

    public static function load(string $path): self
    {
        $instance = new self($path);

        if (! is_file($path)) {
            return $instance;
        }

        $raw = file_get_contents($path);

        if ($raw === false) {
            throw new \RuntimeException(sprintf('[Soak Time] Failed to read integrity lock file at %s', $path));
        }

        if (trim($raw) === '') {
            throw new \RuntimeException(sprintf(
                "[Soak Time] Integrity lock file is empty.\n".
                "  Path: %s\n".
                '  Refusing to run — silently re-pinning would defeat the point.',
                $path
            ));
        }

        try {
            $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw new \RuntimeException(sprintf(
                "[Soak Time] Integrity lock file is malformed JSON: %s\n".
                "  Path: %s\n".
                "  Refusing to run — silently re-pinning would defeat the point.\n".
                '  Fix the JSON, or delete the file to rebuild from scratch (TOFU).',
                $e->getMessage(),
                $path
            ), 0, $e);
        }

        if (! is_array($decoded) || ! array_key_exists('packages', $decoded) || ! is_array($decoded['packages'])) {
            throw new \RuntimeException(sprintf(
                "[Soak Time] Integrity lock file has an invalid structure.\n".
                "  Path: %s\n".
                '  Expected a JSON object with a "packages" object.',
                $path
            ));
        }

        foreach ($decoded['packages'] as $name => $versions) {
            if (! is_string($name) || ! is_array($versions)) {
                throw new \RuntimeException(sprintf(
                    "[Soak Time] Integrity lock file has an invalid package entry.\n".
                    "  Path: %s\n".
                    '  Package keys must be package names and values must be version objects.',
                    $path
                ));
            }

            foreach ($versions as $version => $entryData) {
                if (! is_string($version) || ! is_array($entryData)) {
                    throw new \RuntimeException(sprintf(
                        "[Soak Time] Integrity lock file has an invalid entry for %s@%s.\n".
                        "  Path: %s\n".
                        '  Each version entry must be an object.',
                        $name,
                        is_string($version) ? $version : '<invalid>',
                        $path
                    ));
                }

                $instance->entries[$name][$version] = self::parseEntry($path, $name, $version, $entryData);
            }
        }

        return $instance;
    }

    public function lookup(string $name, string $version): ?IntegrityEntry
    {
        return $this->entries[$name][$version] ?? null;
    }

    public function record(IntegrityEntry $entry): void
    {
        $this->entries[$entry->name][$entry->version] = $entry;
    }

    public function save(): void
    {
        $packages = [];
        $names = array_keys($this->entries);
        sort($names);

        foreach ($names as $name) {
            $versions = array_keys($this->entries[$name]);
            sort($versions);

            foreach ($versions as $version) {
                $packages[$name][$version] = $this->entries[$name][$version]->toArray();
            }
        }

        $payload = [
            '_readme' => self::README,
            '_version' => self::SCHEMA_VERSION,
            'packages' => $packages,
        ];

        $json = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        $tmp = $this->path.'.tmp';

        if (file_put_contents($tmp, $json."\n") === false) {
            throw new \RuntimeException(sprintf('Failed to write integrity lock at %s', $tmp));
        }

        if (! rename($tmp, $this->path)) {
            @unlink($tmp);

            throw new \RuntimeException(sprintf('Failed to move integrity lock into place at %s', $this->path));
        }
    }

    /**
     * @param  array<string, mixed>  $raw
     */
    private static function parseEntry(string $path, string $name, string $version, array $raw): IntegrityEntry
    {
        $sha256 = $raw['sha256'] ?? null;
        $firstSeenAt = $raw['firstSeenAt'] ?? null;

        if ($sha256 !== null) {
            if (! is_string($sha256) || preg_match('/^[a-f0-9]{64}$/i', $sha256) !== 1) {
                throw self::invalidEntry($path, $name, $version, 'sha256 must be null or a 64-character hex string.');
            }

            $sha256 = strtolower($sha256);
        }

        if (! is_string($firstSeenAt) || $firstSeenAt === '') {
            throw self::invalidEntry($path, $name, $version, 'firstSeenAt must be a non-empty timestamp string.');
        }

        try {
            $firstSeen = new \DateTimeImmutable($firstSeenAt);
        } catch (\Exception) {
            throw self::invalidEntry($path, $name, $version, 'firstSeenAt must be a valid timestamp.');
        }

        $sourceReference = self::nullableString($path, $name, $version, $raw, 'sourceReference');
        $sourceUrl = self::nullableString($path, $name, $version, $raw, 'sourceUrl');
        $distUrl = self::nullableString($path, $name, $version, $raw, 'distUrl');

        if ($sha256 === null && $sourceReference === null) {
            throw self::invalidEntry(
                $path,
                $name,
                $version,
                'entry must contain at least one integrity proof: sha256 or sourceReference.'
            );
        }

        return new IntegrityEntry(
            $name,
            $version,
            $sha256,
            $sourceReference,
            $sourceUrl,
            $distUrl,
            $firstSeen,
        );
    }

    /**
     * @param  array<string, mixed>  $raw
     */
    private static function nullableString(
        string $path,
        string $name,
        string $version,
        array $raw,
        string $field,
    ): ?string {
        if (! array_key_exists($field, $raw) || $raw[$field] === null) {
            return null;
        }

        if (! is_string($raw[$field]) || $raw[$field] === '') {
            throw self::invalidEntry($path, $name, $version, sprintf('%s must be null or a non-empty string.', $field));
        }

        return $raw[$field];
    }

    private static function invalidEntry(string $path, string $name, string $version, string $reason): \RuntimeException
    {
        return new \RuntimeException(sprintf(
            "[Soak Time] Integrity lock file has an invalid entry for %s@%s.\n".
            "  Path: %s\n".
            '  %s',
            $name,
            $version,
            $path,
            $reason
        ));
    }
}
