<?php

namespace Innobrain\SoakTime;

final class IntegrityLockFile
{
    private const SCHEMA_VERSION = 1;

    private const README = [
        'Generated by innobrain/soak-time. Records the SHA-256 of every package',
        'version downloaded into this project. Commit alongside composer.lock.',
        'A mismatch against a recorded hash on a later install hard-fails the',
        'run — the signal of an altered historical release.',
    ];

    /** @var array<string, array<string, IntegrityEntry>> */
    private array $entries = [];

    public function __construct(public readonly string $path) {}

    public static function load(string $path): self
    {
        $instance = new self($path);

        if (! is_file($path)) {
            return $instance;
        }

        $raw = file_get_contents($path);

        if ($raw === false || $raw === '') {
            return $instance;
        }

        try {
            $decoded = json_decode($raw, true, 512, JSON_THROW_ON_ERROR);
        } catch (\JsonException $e) {
            throw new \RuntimeException(sprintf(
                "[Soak Time] Integrity lock file is malformed JSON: %s\n".
                "  Path: %s\n".
                "  Refusing to run — silently re-pinning would defeat the point.\n".
                '  Fix the JSON, or delete the file to rebuild from scratch (TOFU).',
                $e->getMessage(),
                $path
            ), 0, $e);
        }

        if (! is_array($decoded) || ! isset($decoded['packages']) || ! is_array($decoded['packages'])) {
            return $instance;
        }

        foreach ($decoded['packages'] as $name => $versions) {
            if (! is_string($name) || ! is_array($versions)) {
                continue;
            }

            foreach ($versions as $version => $entryData) {
                if (! is_string($version) || ! is_array($entryData)) {
                    continue;
                }

                $entry = self::parseEntry($name, $version, $entryData);

                if ($entry !== null) {
                    $instance->entries[$name][$version] = $entry;
                }
            }
        }

        return $instance;
    }

    public function lookup(string $name, string $version): ?IntegrityEntry
    {
        return $this->entries[$name][$version] ?? null;
    }

    public function record(IntegrityEntry $entry): void
    {
        $this->entries[$entry->name][$entry->version] = $entry;
    }

    public function save(): void
    {
        $packages = [];
        $names = array_keys($this->entries);
        sort($names);

        foreach ($names as $name) {
            $versions = array_keys($this->entries[$name]);
            sort($versions);

            foreach ($versions as $version) {
                $packages[$name][$version] = $this->entries[$name][$version]->toArray();
            }
        }

        $payload = [
            '_readme' => self::README,
            '_version' => self::SCHEMA_VERSION,
            'packages' => $packages,
        ];

        $json = json_encode($payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_THROW_ON_ERROR);
        $tmp = $this->path.'.tmp';

        if (file_put_contents($tmp, $json."\n") === false) {
            throw new \RuntimeException(sprintf('Failed to write integrity lock at %s', $tmp));
        }

        if (! rename($tmp, $this->path)) {
            @unlink($tmp);

            throw new \RuntimeException(sprintf('Failed to move integrity lock into place at %s', $this->path));
        }
    }

    /**
     * @param  array<string, mixed>  $raw
     */
    private static function parseEntry(string $name, string $version, array $raw): ?IntegrityEntry
    {
        $sha256 = $raw['sha256'] ?? null;
        $firstSeenAt = $raw['firstSeenAt'] ?? null;

        if (! is_string($sha256) || $sha256 === '' || ! is_string($firstSeenAt)) {
            return null;
        }

        try {
            $firstSeen = new \DateTimeImmutable($firstSeenAt);
        } catch (\Exception) {
            return null;
        }

        $sourceReference = $raw['sourceReference'] ?? null;
        $distUrl = $raw['distUrl'] ?? null;

        return new IntegrityEntry(
            $name,
            $version,
            $sha256,
            is_string($sourceReference) ? $sourceReference : null,
            is_string($distUrl) ? $distUrl : null,
            $firstSeen,
        );
    }
}
